# Generated by Django 5.0.6 on 2024-06-20 22:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte své jméno', max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(help_text='Zadejte své příjmení', max_length=50, verbose_name='Příjmení')),
                ('email', models.EmailField(help_text='Zadejte svůj Emal', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platnou emailovou adresu.', regex='^[A-Za-z]+@[A-Za-z]+\\.[A-Za-z]+$')], verbose_name='Email')),
                ('tel', models.CharField(help_text='Zadejte své telefonní číslo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Tel. číslo')),
                ('adresa', models.CharField(help_text='Zadejte svou adresu', max_length=255, verbose_name='Adresa')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte své jméno', max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(help_text='Zadejte své příjmení', max_length=50, verbose_name='Příjmení')),
                ('email', models.EmailField(help_text='Zadejte svůj Emal', max_length=254, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platnou emailovou adresu.', regex='^[A-Za-z]+@[A-Za-z]+\\.[A-Za-z]+$')], verbose_name='Email')),
                ('tel', models.CharField(help_text='Zadejte své telefonní číslo', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Tel. číslo')),
                ('adresa', models.CharField(help_text='Zadejte svou adresu', max_length=255, verbose_name='Adresa')),
            ],
        ),
        migrations.CreateModel(
            name='Auta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen')], max_length=50)),
                ('barva', models.CharField(choices=[('Červená', 'Červená'), ('Modrá', 'Modrá'), ('Zelená', 'Zelená'), ('Černá', 'Černá'), ('Bílá', 'Bílá'), ('Šedá', 'Šedá')], max_length=50)),
                ('stav', models.CharField(choices=[('Nový', 'Nový'), ('Použitý', 'Použitý'), ('Poškozený', 'Poškozený')], max_length=20)),
                ('popis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auta', to='auta.customer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auta', to='auta.dealer')),
            ],
        ),
    ]
